### ISSUE TITLE
typo and poor description

### ISSUE THREAD

**Issue by utzl** [jupadin/MMM-RNV#1]
thanks for the update.
In MMM-RNV.js there is a typo in line 35: "cliendID" instead of "cientID".

Unfortunately the application only shows "Loading" with my credentials from the RNV data hub and is not working.
I received these credentials:
@clientID=ba589733-8724-4f95-b4d0-b9f18a0*****
@tenantID=87cd3c4f-1e0a-4350-889e-3969cd4*****
@clientSecret=JzuJc-4Ed~BXl4w2I.B8JUu.b0GEn*****
@resource=1484212f-edce-452a-aae9-46141ba*****
@scope=https://rnv-dds-sandbox-graphqlextern.azurewebsites.net/user_impersonation
@hostname=https://graphql-sandbox-dds.rnv-online.de

--> oAuthURL == scope?
--> tenantID is not necessary?

please update the description for users without an api key. Thanks.

**Comment by jupadin** [comment]
Hi,
thanks for your issue.
I modified the code such that now it should be possible to generate an apiKey with the given credentials and use the module.

I also added more information in the readme regarding the given credentials.
The oAuthURL has to be the URL given by @scope and the tenantID is not necessary, right.

**Comment by utzl** [comment]
Hi, many thanks for the immediate fix.
Unfortunately the module is not running on my Pi.
Here is the log, hopefully you can find a reason:

[29.06.2021 21:22.11.139] [LOG]   MMM-RNV: Fetching data from RNV-Server...
[29.06.2021 21:22.11.149] [LOG]   MMM-RNV: Fetching data from RNV-Server...
[29.06.2021 21:22.11.162] [LOG]   Error while querying data from server:
 ApolloError: Network error: Unexpected token Y in JSON at position 0
    at new ApolloError (/home/pi/MagicMirror/modules/MMM-RNV/node_modules/apollo-client/bundle.umd.js:92:26)
    at /home/pi/MagicMirror/modules/MMM-RNV/node_modules/apollo-client/bundle.umd.js:1588:34
    at /home/pi/MagicMirror/modules/MMM-RNV/node_modules/apollo-client/bundle.umd.js:2008:15
    at Set.forEach (<anonymous>)
    at /home/pi/MagicMirror/modules/MMM-RNV/node_modules/apollo-client/bundle.umd.js:2006:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/home/pi/MagicMirror/modules/MMM-RNV/node_modules/apollo-client/bundle.umd.js:2004:20)
    at /home/pi/MagicMirror/modules/MMM-RNV/node_modules/apollo-client/bundle.umd.js:1483:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  graphQLErrors: [],
  networkError: SyntaxError [ServerParseError]: Unexpected token Y in JSON at position 0
      at JSON.parse (<anonymous>)
      at /home/pi/MagicMirror/modules/MMM-RNV/node_modules/apollo-link-http-common/lib/index.js:35:25
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    name: 'ServerParseError',
    response: Response {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    },
    statusCode: 401,
    bodyText: 'You do not have permission to view this directory or page.'
  },
  message: 'Network error: Unexpected token Y in JSON at position 0',
  extraInfo: undefined
}

**Comment by jupadin** [comment]
This might be the reason of an invalid access token / apiKey.
The generated key is only valid for a certain amount of time until it has to be refreshed.
Currently I'm working on this refresh method and try to implement as soon as possible.
