### ISSUE TITLE
Module stops refreshing, if there was an error

### ISSUE THREAD

**Issue by jalibu** [jupadin/MMM-RNV#2]
Servus Julian,
tolles Modul.

Kleines Fehlerchen:
Wenn im node_helper der Client Request in den Catch Block in Zeile 166 läuft (z.B. weil es ein Connection Timeout gab), dann stellt das Modul leider seine Arbeit ein, weil das setTimeout nicht mehr durchlaufen wird.

**Comment by jupadin** [comment]
Hey,
ja, das ist eigentlich so beabsichtigt, weil dann keine credentials gegeben sind, sondern nur ein aktuell funktionierender API-Key.
Nachdem dieser nicht mehr gültig ist, kann, aufgrund der fehlenden credentials kein neuer API-Key mehr generiert werden und daraufhin soll der user darüber benachrichtigt werden.

**Comment by HeisemerBub** [comment]
Hallo Julian, ich wollte dein Modul für Magic Mirror nutzen...habe es über console in den module ordner installiert wie beschrieben mit npm install....danach habe ich in der Magicmirror config datei folgendes eingetragen:

{
            module: 'MMM-RNV',
            header: 'RNV Abfahrstmonitor',
            position: 'top_right',
            config: {
                apiKey: 'Enter your apiKey here',
                // or
                clientID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                tenantID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                clientSecret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                resourceID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            },
				header: "RNV Abfahrtsmonitor",
				stationId: "1585",
				numJourneys: "10",
				updateInterval: "60000",
				animationSpeed: "2000",
				coloredLines: "true",
				showLineIcons: "true",
				useColorForRealTimeInfo: "true",
				showTableHeader: "true",
	},
API direkt hat mir die RNV nicht zugesendet...nur die ID´s!!

nach einem Start des MM kommt aber nur Lade......

Was mache ich falsch?
Über ne kurze Rückinfo herzlichen Dank

Gruss
Kussel

muss ich da den GraphQL API eintragen oder den gtfs-rt Endpoint?
