### ISSUE TITLE
MagicMirror - keine Anzeige

### ISSUE THREAD

**Issue by HeisemerBub** [jupadin/MMM-RNV#3]
Hallo Julian, ich wollte dein Modul für Magic Mirror nutzen...habe es über console in den module ordner installiert wie beschrieben mit npm install....danach habe ich in der Magicmirror config datei folgendes eingetragen:

{
module: 'MMM-RNV',
header: 'RNV Abfahrstmonitor',
position: 'top_right',
config: {
apiKey: 'Enter your apiKey here',
// or
clientID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
tenantID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
clientSecret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
resourceID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
},
header: "RNV Abfahrtsmonitor",
stationId: "1585",
numJourneys: "10",
updateInterval: "60000",
animationSpeed: "2000",
coloredLines: "true",
showLineIcons: "true",
useColorForRealTimeInfo: "true",
showTableHeader: "true",
},
API direkt hat mir die RNV nicht zugesendet...nur die ID´s!!

nach einem Start des MM kommt aber nur Lade......

Was mache ich falsch?
Über ne kurze Rückinfo herzlichen Dank

Gruss
Kussel

**Comment by jupadin** [comment]
Hallo kusselin,

bei der in der Konfigurationsdatei musst Du Dich zwischen dem `apiKey` oder `clientID`, `tenantID`, `clientSecret` und `resourceID` entscheiden.
Sprich entweder trägst Du direkt den APIKey ein oder die anderen nötigen Daten, damit der Key automatisch bei Bedarf generiert werden kann.
Das Problem liegt hier in dieser Zeile:
```
apiKey: 'Enter your apiKey here',
```
Das Modul denkt, dass du hiermit den APIKey angegeben hast und versucht dann die Daten abzurufen, was nicht funktioniert, da `Enter your apiKey here` kein valider APIKey ist.
Ein Entfernen der Zeilen
```
apiKey: 'Enter your apiKey here',
// or
```
sollte das Problem beheben.
Deine Konfiguration sollte dann so aussehen:
```
{
  module: 'MMM-RNV',
  header: 'RNV Abfahrstmonitor',
  position: 'top_right',
  config: {
    clientID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    tenantID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    clientSecret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    resourceID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  },
    header: "RNV Abfahrtsmonitor",
    stationID: "1585",
    numJourneys: "10",
    updateInterval: "60000",
    animationSpeed: "2000",
    coloredLines: "true",
    showLineIcons: "true",
    useColorForRealTimeInfo: "true",
    showTableHeader: "true",
},
```

Die RNV sendet immer nur die ID's zu - anschließend kann man den APIKey entweder selbst generieren oder (bei Angabe dieser ID's) sich über das Modul automatisch generieren lassen, welcher dann direkt auch verwendet wird.
Die Angabe der ID's ist somit vollkommen ausreichend.

Grüße
Julian

**Comment by HeisemerBub** [comment]
Hi Julian danke vorab..welche iDs muss ich nehmen? 
Die GraphQL API oder den gtfs-rt Endpoint…
Die habe ich nämlich von der RNV zugesandt bekommen…

Andonsten stimmt sber das Format so mit den klammern?

Gruss
Markus

**Comment by jupadin** [comment]
Hallo Markus,

es sollten die GraphQL API ID's sein.
Ich habe aber gerade gesehen, dass die RNV deren API-Schnittstelle geändert haben - sitze gerade dran das anzupassen.
Das Format sollte so eigentlich passen: Das Config-Feld als auch die einzelnen Module sind jeweils einzelne Dictionaries.

Bezüglich der Schnittstelle würde ich mich einfach nochmal melden, wenn ich mehr Infos habe.

**Comment by HeisemerBub** [comment]
Hi Julian….,

 

super und vielen herzlichen Dank.

 

Es gibt ja noch ein Modul von Jalibu..

 

https://github.com/jalibu/MMM-RNV

 

Deines sieht aber bissl anders aus……..habe es mal mit dem jalibu auch probiert aber da kommen auch keine Daten an..steht nur „Lade….“

 

Kannst du deines auch so abkupfern mit der Station ID usw…

 

Gruss

 

Markus

**Comment by jupadin** [comment]
Hallo Markus,

das Modul von Jalibu basiert auf meinem Modul und taucht da vermutlich das selbe Problem auf.
Die StationID ist auch bei meinem Modul vorhanden - siehe Konfigurationsoptionen.

Grüße

**Comment by HeisemerBub** [comment]
So, habs mal geändert und den API rausgenommen….funzt 😊

 

Nur..ich habe bei Station ID die 1585 eingtragen lt. Liste und er zeigt mir aber den Abfahrtsmonitor von Mannheim Hauptbahnhof an…..

 

Siehe mein post

 

Was ist da falsch noch?

 

Gruss

**Comment by jupadin** [comment]
Hi Markus,

das liegt daran, dass in Deiner Konfiguration (s.o.) vermutlich `stationId` anstatt `stationID` steht. (Beachte den Buchstaben "d" bzw. "D" bei `stationID`).
Mannheim HBF ist als Default-Wert eingetragen, sofern er keine `stationID` in der Konfiguration findet...

Freut mich, dass das Modul jetzt funktioniert ! 👍

**Comment by HeisemerBub** [comment]
Nein…geht immer noch nicht..so siehts aus jetzt also da wird schon was angezeigt aber nicht die richtige Station..immer Mannheim hauptbahnhof ☹

 

{

                              module: 'MMM-RNV',

                              header: 'RNV Abfahrstmonitor',

                              position: 'top_right',

                              config: {

                              clientID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',

                              tenantID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',

                              clientSecret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',

                              resourceID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',

                              },

                              header: "RNV Abfahrtsmonitor",

                              stationID: "1585",

                              numJourneys: "10",

                              updateInterval: "60000",

                              animationSpeed: "2000",

                              coloredLines: "true",

                              showLineIcons: "true",

                              useColorForRealTimeInfo: "true",

                              showTableHeader: "true",

                              },

**Comment by HeisemerBub** [comment]
Schau:

**Comment by jupadin** [comment]
Hi Markus,

wäre es möglich über GiHub zu antworten, da sonst der ganze Verlauf immer mitgesendet wird und das sehr unübersichtlich ist.
Eine (spontane) Idee wäre noch folgende Option:
```
stationID: 1585
```
und
```
numJourneys: 10
```

Also Integers statt Strings.

**Comment by HeisemerBub** [comment]
Hi, nein..auch das bringt kein Erfolg :-( ev. liegt das am Code......
so sieht meine config jetzt akuell aus:

{
		module: 'MMM-RNV',
		header: 'RNV Abfahrstmonitor',
		position: 'top_right',
		config: {
		clientID: 'xxxxx',
		tenantID: 'xxxxxx',
		clientSecret: 'xxxxxxxx',
		resourceID: 'xxxxx',
		},
		header: "RNV Abfahrtsmonitor",
		**stationID: 2594,
		numJourneys: 10,**
		updateInterval: "60000",
		animationSpeed: "2000",
		coloredLines: "true",
		showLineIcons: "true",
		useColorForRealTimeInfo: "true",
		showTableHeader: "true",
		}, 

kann das am doppelten "Header" liegen???

EDIT: Nein am doppelten "Header" liegts auch nicht......das muss irgendwie mit dem Code zu tun haben...da bin ich aber raus jetzt........

schreib mir einfach wenn ich was ändern soll 

Frohe weihnachten Dir noch...

Gruss

**Comment by jalibu** [comment]
Die Properties stationID bis showTableHeader gehören ins config Objekt.

**Comment by jupadin** [comment]
Da hat jalibu natürlich absolut recht.
Anbei die Konfiguration, wie sie mit den gewünschten Optionen aussehen sollte:
```
 {
  module: 'MMM-RNV',
  header: 'RNV Abfahrstmonitor',
  position: 'top_right',
  config: {
    updateInterval: "60000",
    animationSpeed: "2000",
    stationID: "2594",
    numJourneys: "10",
    clientID: 'Enter your @clientID here',
    tenantID: 'Enter your @tenantID here',
    clientSecret: 'Enter your @clientSecret here',
    resourceID: 'Enter your @resource here',
    coloredLines: "true",
    showLineIcons: "true",
    useColorForRealTimeInfo: "true",
    showTableHeader: "true",
  }
}

**Comment by HeisemerBub** [comment]
o.k. aber dann muss auch die Beschreibung und und das Beislpiel in github geändert werden Julian..

Gruss

**Comment by HeisemerBub** [comment]
{
  module: 'MMM-RNV',
  header: 'RNV Abfahrstmonitor',
  position: 'top_right',
  config: {
    updateInterval: "60000",
    animationSpeed: "2000",
    stationId: "2594",
    numJourneys: "10",
    clientID: 'Enter your @clientID here',
    tenantID: 'Enter your @tenantID here',
    clientSecret: 'Enter your @clientSecret here',
    resourceID: 'Enter your @resource here',
    coloredLines: "true",
    showLineIcons: "true",
    useColorForRealTimeInfo: "true",
    showTableHeader: "true",
  }
},

Nein geht immer noch nicht so!!! Weiterhin wird der HBHF Mannheim angezeigt....Uhrzeiten usw. funzen.....

Mensch, warum klappt das nicht??

Gruss

**Comment by jupadin** [comment]
Da ist ein Tippfehler in `stationId` -  es muss `stationID` mit "D" statt "d" sein.

Grüße

**Comment by HeisemerBub** [comment]
{
module: 'MMM-RNV',
header: 'RNV Abfahrstmonitor',
position: 'top_right',
config: {
updateInterval: "60000",
animationSpeed: "2000",
stationID: "2594",
numJourneys: "10",
clientID: 'Enter your @clientID here',
tenantID: 'Enter your @TenantID here',
clientSecret: 'Enter your @clientSecret here',
resourceID: 'Enter your @resource here',
coloredLines: "true",
showLineIcons: "true",
useColorForRealTimeInfo: "true",
showTableHeader: "true",
}
},

Danke, das war der entscheidende Tipp!! Nun läuft alles so wie gepostet Danke euch allen nochmals...vielleicht hilfts anderen auch mal....

Frohe Weihnachten noch Euch

**Comment by HeisemerBub** [comment]
ne Frage habe ich noch..ich harbeiote mit dem MMM-Carousel udn da wollte ich jetzt noch in einen Slide den HBF MA und Heidelberg HBF einfügen......geht das ? wisst Ihr das?

**Comment by jalibu** [comment]
Ich würde sagen, dass das weder mit jupadins, noch mit meiner Implementierung so einfach funktioniert, da sie beide keine Mehrfach-Instanzen unterstützen.

**Comment by jalibu** [comment]
@kusselin da ich das grundsätzlich als wichtiges Feature betrachte und nur 2-3 kleine Anpassungen nötig waren, habe ich das bei meiner Implementierung angepasst. Du kannst das Modul nun einfach mehrfach in deine Config eintragen und mit Carousel entsprechend das eine oder das andere einblenden lassen.

Falls du jupadins Version gerne weiter verwenden möchtest, kann dieser ja gerne bei mir spicken wie es geht :-)

**Comment by HeisemerBub** [comment]
Super das freut mich das du das auch so siehst…
Gruss und danke für die Arbeit :-)

**Comment by HeisemerBub** [comment]
Ne Frage noch…du kennst das Carousel modul?

Da gibbet mehrere Slides

Wie gebe ich das dann an das carousel weiss das ist RNV 1 das RNV 2 usw ? Also in der Config
Gruss

**Comment by jalibu** [comment]
Keine Ahnung wie das bei Carousel funktioniert. Ich verwende MMM-pages, da steuert man das über classes

**Comment by HeisemerBub** [comment]
Ja pages kenne ich auch..nur wenn du wetter anzeigen lasst also das mm standardwetter wird dieses bei pages nicht angezeigt :-(

Sonst hätte ich es auch

**Comment by HeisemerBub** [comment]
Hallo Jahn, wenn ich aber den Code hier mehrfach in meine comnfig kopiere udn die StationID ändere dann heisst das madul aber b ei allen "MMM-RNV"

Wenn wie soll ich das dann in Carousel oder pages eintragen??? Hier müsste es dann so sein..für slide 1 das MMM-RNV1 für slide 2 MMM-RNV2 und RNV3

weiss du was ich meine?

In den Slides kann ich nur MMM-RNV eintragen....das Carousel oder Pages weiss dann aber nicht welches ?

Gruss

**Comment by jupadin** [comment]
Hey,
ich schließe das Issue hier mal - das eigentliche Problem ist (hoffentlich) jetzt gelöst.

Gerne neue Funktionalität über ein Feature Request oder direkt bei jalibu weiter kommunizieren.
Danke!

**Comment by jupadin** [comment]
> Ich würde sagen, dass das weder mit jupadins, noch mit meiner Implementierung so einfach funktioniert, da sie beide keine Mehrfach-Instanzen unterstützen.

Das stimmt so leider nicht ganz.
Mit der aktuellen Implementierung funktioniert mein Modul auch mit Mehrfach-Instanzen - Danke!


Zu dem eigentlichen Problem:

> Hallo Jahn, wenn ich aber den Code hier mehrfach in meine comnfig kopiere udn die StationID ändere dann heisst das madul aber b ei allen "MMM-RNV"

@kusselin: Hier muss in der Konfiguration lediglich der Header von `RNV-Abfahrsmonitor` zu `RNV-Abfahrtsmonitor 1` oder dem, was dort stehen soll, geändert werden.

**Comment by HeisemerBub** [comment]
Hi Jungs…

Bitte dann sagt mir bitte wie ich das verwirklichen kann mit der Mehrfachinstanz???

Ich wäre sehr dankbar
Gruss
