### ISSUE TITLE
API Verlängerung

### ISSUE THREAD

**Issue by HeisemerBub** [jupadin/MMM-RNV#4]
Hallo Julian, wir hatten glaube ich vor einem Jahr mal schon Kontakt bzg. deinem MMM-RNV Modul....und der Config.
Hat bis jetzt alles Prima funktioniert bis letztens...da wurde nicht mehr angezeigt im MM. Ich habe daraufhin die RNV angeschrieben udn jetzt haben Sie mir folgendes gesendet per eMail:

hier die Credentials, aus unserem Portal:

  Client ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  Secret Text: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Ich hoffe, dass ich Ihnen damit weiterhelfen konnte. Die Gültigkeit
des Key wird im System nur verlängert. Der Key ändert sich nicht.

und hier noch meine config:

{
		  module: 'MMM-RNV',
		  header: 'RNV Abfahrstmonitor',
		  position: 'bottom_center',
		  config: {
			updateInterval: "60000",
			animationSpeed: "2000",
			stationID: "1160", // HD-Bahnhof
			numJourneys: "10",
			clientID: 'xxxxxxxxxxxxxxxxxxxxxxx',
			tenantID: '87xxxxxxxxxxxxxxxxxxxxxxx',
			clientSecret: 'xxxxxxxxxxxxxxxxxAyT4gaxxxxxxxxx0',
			resourceID: '1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
			coloredLines: "true",
			showLineIcons: "true",
			useColorForRealTimeInfo: "true",
			showTableHeader: "true",
		  }
		},
Es gibt doch aber noch die resourceID und tenantID

Benötige ich diese dann nicht oder bleibt die auch gleich...wenn ich die beiden Sachen ändere clientID und secret text alias clientSecret wird nichts angezeigt und im MM wird immer angezeigt:

`No API credentials provided`

Weisst Du woran das liegen kannn?
Über ne Info herzlichen Dank

Gruss
Heisemer

**Comment by jupadin** [comment]
Hallo Heisemer,

laut Deinen Infos würde ich schließen, dass sich die resourceID und tenantID dann nicht ändern.
Analog der Antwort von @jalibu in https://github.com/jalibu/MMM-RNV/issues/4#issuecomment-1289334193 sollten die Modulkonfigurationsoptionen direkt als Boolean-Werte angegeben werden:
```{
  module: 'MMM-RNV',
  header: 'RNV Abfahrstmonitor',
  position: 'bottom_center',
  config: {
    updateInterval: "60000",
    animationSpeed: "2000",
    stationID: "1160", // HD-Bahnhof
    numJourneys: "10",
    clientID: 'xxxxxxxxxxxxxxxxxxxxxxx',
    tenantID: '87xxxxxxxxxxxxxxxxxxxxxxx',
    clientSecret: 'xxxxxxxxxxxxxxxxxAyT4gaxxxxxxxxx0',
    resourceID: '1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    coloredLines: true,
    showLineIcons: true,
    useColorForRealTimeInfo: true,
    showTableHeader: true,
  }
}
```

Für eine detailliertere Fehlersuche wäre ggfs. ein Blick in die Logs super - möglicher Ansatzpunkt wäre hier zu überprüfen, ob ein entsprechender Token aus den Credentials erzeugt wird.
Ich würde detailliertere Logs auch nochmal im Code hinzufügen, sodass wir das Problem sicherlich finden können.

Liebe Grüße

**Comment by HeisemerBub** [comment]
Ich habe den Fehler gefunden...ich habe die Config von Dir genommen das Modul aber von Jan installiert..oh mann..

Jetzt gehts!
Danke Dir und Jan
